[project]
name = "ipum-lab-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "pre-commit>=4.2.0",
    "pydantic-settings>=2.9.1",
    "pyyaml>=6.0.2",
    "uvicorn>=0.29.0",
    "fastapi>=0.110.0",
    "joblib>=1.4.0",
    "scikit-learn>=1.4.0",
    "pandas>=2.2.0",
    "numpy>=1.26.0",
    "pytest>=7.4.0",              # do testów
    "pytest-dotenv>=0.5.2",       # ładowanie .env.test
    "httpx>=0.26.0",              # do TestClient
    "typing-extensions>=4.9.0"    # zgodna z pydantic-core
]